[package]
name = "pc4d-rust"
version = "0.1.0"
authors = ["Daniel Mikusa <dan@mikusa.com>"]
edition = "2018"

[dependencies]
sodiumoxide = "0.2"
hex = "0.4"
base64 = "0.12"
sha3 = "0.9"
digest = "0.9"